
version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:876983010549:task-definition/pod3-auth-taskdfn:1"
        LoadBalancerInfo:
          ContainerName: "auth-pod3"
          ContainerPort: "9095"
        PlatformVersion: "LATEST"

