
version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:876983010549:task-definition/pod3-pharmacysupply-taskdfn:1"
        LoadBalancerInfo:
          ContainerName: "pharmacysupply-pod3"
          ContainerPort: "8083"
        PlatformVersion: "LATEST"

