
version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-2:876983010549:task-definition/pod3-medrep-taskdefn:1"
        LoadBalancerInfo:
          ContainerName: "medrep-pod3"
          ContainerPort: "8081"
        PlatformVersion: "LATEST"

