FROM adoptopenjdk/openjdk11
WORKDIR /
ADD MedicalRepresentativeMicroService-0.0.1-SNAPSHOT.jar MedicalRepresentativeMicroService-0.0.1-SNAPSHOT.jar
EXPOSE 8081
CMD java -jar MedicalRepresentativeMicroService-0.0.1-SNAPSHOT.jar